ARG ELIXIR_VERSION=1.17.2
ARG OTP_VERSION=27.0.1
ARG DEBIAN_VERSION=bullseye-20240722-slim
ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE}

# Set development environment
ENV MIX_ENV=dev

# Install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git curl inotify-tools \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && apt-get install -y nodejs

# Set working directory
WORKDIR /app

# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Install Phoenix
RUN mix archive.install hex phx_new --force

# Copy mix files
COPY mix.exs mix.lock ./

# Install mix dependencies
RUN mix deps.get

# Copy config files
COPY config config

# Copy the rest of the application code
COPY . .

# Install npm dependencies
WORKDIR /app/assets
RUN npm install

# Return to the app directory
WORKDIR /app

# Expose port 4000 (default for Phoenix)
EXPOSE 4000

# Start Phoenix server
CMD ["mix", "phx.server"]